#pragma once

//Definitions for User Program project: CNCMotions_specifications
//Located at: C:\Users\User\OneDrive - Akribis Systems\_root\User Program Library\CNCMotions_specifications
//Note: array defines are transcribed to 'underscore', i.e. SomeVar[1] => SomeVar_1

//DefineVar directives
#define aaxis "AGenData[800]"	//From file: cncmotions_specifications.pup2


//Define directives
#define MY_EXAMPLE1 "10000"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_LINEAR "1"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_ARC "2"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_SET_VECTOR_PARAMS "5"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_CORNER_PARAMS "6"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_DOUTPORT_WRITE "8"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_ARRAY_WRITE "9"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_WAIT_ARRAY "12"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_AUTOMATIC_CORNER "14"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_ARRAY_WRITE_MULTIPLE "17"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_ARRAY_WRITE_MULTIPLE_WAIT "18"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_WAIT_INPUT "21"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_SPATIAL_EVENTS_SETUP "22"	//From file: cncmotions_specifications.pup2
#define CNC_SEGMENT_TYPE_SPATIAL_EVENTS "23"	//From file: cncmotions_specifications.pup2
#define NONINV_UNUSED_MASK "0x00FFFFFF"	//From file: cncmotions_specifications.pup2
#define ONEINV_UNUSED_MASK "0x000FFFFF"	//From file: cncmotions_specifications.pup2
#define TWOINV_UNUSED_MASK "0x0000FFFF"	//From file: cncmotions_specifications.pup2
#define THREEINV_UNUSED_MASK "0x00000FFF"	//From file: cncmotions_specifications.pup2
#define FOURINV_UNUSED_MASK "0x000000FF"	//From file: cncmotions_specifications.pup2
#define FIVEINV_UNUSED_MASK "0x0000000F"	//From file: cncmotions_specifications.pup2
#define ARRAY_TYPE_GENDATA "0"	//From file: cncmotions_specifications.pup2
#define ARRAY_TYPE_USERPARAM "1"	//From file: cncmotions_specifications.pup2
#define INPUT_SELECTION_DIGITAL "0"	//From file: cncmotions_specifications.pup2
#define INPUT_SELECTION_ANALOG "1"	//From file: cncmotions_specifications.pup2
#define CNC_TRIG_NONE "0"	//From file: cncmotions_specifications.pup2
#define CNC_TRIG_GT "1"	//From file: cncmotions_specifications.pup2
#define CNC_TRIG_EQ "2"	//From file: cncmotions_specifications.pup2
#define CNC_TRIG_NE "3"	//From file: cncmotions_specifications.pup2
#define CNC_TRIG_LT "4"	//From file: cncmotions_specifications.pup2
#define CNC_TRIG_RIS_EDGE "5"	//From file: cncmotions_specifications.pup2
#define CNC_TRIG_FALL_EDGE "6"	//From file: cncmotions_specifications.pup2
#define CNC_TRIG_MANUAL "7"	//From file: cncmotions_specifications.pup2
#define CNC_TRIG_CHANGED "8"	//From file: cncmotions_specifications.pup2
#define A_AXIS "0"	//From file: cncmotions_specifications.pup2
#define B_AXIS "1"	//From file: cncmotions_specifications.pup2
#define C_AXIS "2"	//From file: cncmotions_specifications.pup2
#define D_AXIS "3"	//From file: cncmotions_specifications.pup2
#define E_AXIS "4"	//From file: cncmotions_specifications.pup2
#define F_AXIS "5"	//From file: cncmotions_specifications.pup2
#define G_AXIS "6"	//From file: cncmotions_specifications.pup2
#define H_AXIS "7"	//From file: cncmotions_specifications.pup2
#define USER_INPUT "0"	//From file: cncmotions_specifications.pup2
#define DEDICATED_HW_FUNCTION "1"	//From file: cncmotions_specifications.pup2
#define MOTOR_ON_INPUT "2"	//From file: cncmotions_specifications.pup2
#define BEGIN_MOTION "3"	//From file: cncmotions_specifications.pup2
#define STOP_MOTION "4"	//From file: cncmotions_specifications.pup2
#define CLEAR_IN_PULSES "5"	//From file: cncmotions_specifications.pup2
#define ABORT_RESUME_MOTION "6"	//From file: cncmotions_specifications.pup2
#define ALARM_RESET "7"	//From file: cncmotions_specifications.pup2
#define ABORT_MOTION "8"	//From file: cncmotions_specifications.pup2
#define REV_LIMIT "9"	//From file: cncmotions_specifications.pup2
#define FWD_LIMIT "10"	//From file: cncmotions_specifications.pup2
#define TORQUE_LIMIT_ON "11"	//From file: cncmotions_specifications.pup2
#define ACTIVATE_DYNAMIC_BRAKE "12"	//From file: cncmotions_specifications.pup2
#define LOCK_STATIC_BRAKE "13"	//From file: cncmotions_specifications.pup2
#define CONTROL_SET_CHANGE "14"	//From file: cncmotions_specifications.pup2
#define ADD_FILTER "15"	//From file: cncmotions_specifications.pup2
#define MODE_SWITCH_VEL_POS "16"	//From file: cncmotions_specifications.pup2
#define MODE_SWITCH_VEL_CUR "17"	//From file: cncmotions_specifications.pup2
#define MODE_SWITCH_POS_CUR "18"	//From file: cncmotions_specifications.pup2
#define CLEAR_ABS_ENC "19"	//From file: cncmotions_specifications.pup2
#define CHANGE_SPEED "20"	//From file: cncmotions_specifications.pup2
#define HOME "21"	//From file: cncmotions_specifications.pup2
#define MODE_SWITCH_POS_FORCE "22"	//From file: cncmotions_specifications.pup2
#define HALL_A "23"	//From file: cncmotions_specifications.pup2
#define FAULT_INPUT "24"	//From file: cncmotions_specifications.pup2
#define HOMING_ON_INPUT "25"	//From file: cncmotions_specifications.pup2
#define FAULT_INPUT_CONTROLLED_STOP "26"	//From file: cncmotions_specifications.pup2
#define HEIDENHAIN_LIMITS "27"	//From file: cncmotions_specifications.pup2
#define DOUT_USER_OUTPUT "0"	//From file: cncmotions_specifications.pup2
#define DOUT_DEDICATED_HW_FUNCTION "1"	//From file: cncmotions_specifications.pup2
#define DOUT_MOTOR_ON "2"	//From file: cncmotions_specifications.pup2
#define DOUT_IN_MOTION "3"	//From file: cncmotions_specifications.pup2
#define DOUT_IN_ACCELERATION "4"	//From file: cncmotions_specifications.pup2
#define DOUT_IN_DECELERATION "5"	//From file: cncmotions_specifications.pup2
#define DOUT_IN_CONSTANT_SPEED "6"	//From file: cncmotions_specifications.pup2
#define DOUT_END_OF_MOTION "7"	//From file: cncmotions_specifications.pup2
#define DOUT_IN_TARGET "8"	//From file: cncmotions_specifications.pup2
#define DOUT_ALARM "9"	//From file: cncmotions_specifications.pup2
#define DOUT_WARNINGS_IN_LAST_MOTION "10"	//From file: cncmotions_specifications.pup2
#define DOUT_SATURATIONS_IN_LAST_MOTION "11"	//From file: cncmotions_specifications.pup2
#define DOUT_RLS_FLS_ACTIVE "12"	//From file: cncmotions_specifications.pup2
#define DOUT_OUT_OF_TRAVEL "13"	//From file: cncmotions_specifications.pup2
#define DOUT_REGENERATION_ACTIVE "14"	//From file: cncmotions_specifications.pup2
#define DOUT_DYNAMIC_BRAKE_ACTIVE "15"	//From file: cncmotions_specifications.pup2
#define DOUT_STATIC_BRAKE_LOCK "16"	//From file: cncmotions_specifications.pup2
#define DOUT_STATIC_UNUSED "17"	//From file: cncmotions_specifications.pup2
#define DOUT_RLS_ACTIVE "18"	//From file: cncmotions_specifications.pup2
#define DOUT_FLS_ACTIVE "19"	//From file: cncmotions_specifications.pup2
#define DOUT_HOMING_STAT "20"	//From file: cncmotions_specifications.pup2
#define DOUT_FORCE_IN_TARGET "21"	//From file: cncmotions_specifications.pup2
#define MAX_OUTPUT_MODE "21"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT1_BIT "0x00000001"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT2_BIT "0x00000002"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT3_BIT "0x00000004"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT4_BIT "0x00000008"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT5_BIT "0x00000010"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT6_BIT "0x00000020"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT7_BIT "0x00000040"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT8_BIT "0x00000080"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT9_BIT "0x00000100"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT10_BIT "0x00000200"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT11_BIT "0x00000400"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT12_BIT "0x00000800"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT13_BIT "0x00001000"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT1_SET "0x00000001"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT2_SET "0x00000002"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT3_SET "0x00000004"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT4_SET "0x00000008"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT5_SET "0x00000010"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT6_SET "0x00000020"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT7_SET "0x00000040"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT8_SET "0x00000080"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT9_SET "0x00000100"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT10_SET "0x00000200"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT11_SET "0x00000400"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT12_SET "0x00000800"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT13_SET "0x00001000"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT1_CLEAR "0xFFFFFFFE"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT2_CLEAR "0xFFFFFFFD"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT3_CLEAR "0xFFFFFFFB"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT4_CLEAR "0xFFFFFFF7"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT5_CLEAR "0xFFFFFFEF"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT6_CLEAR "0xFFFFFFDF"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT7_CLEAR "0xFFFFFFBF"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT8_CLEAR "0xFFFFFF7F"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT9_CLEAR "0xFFFFFEFF"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT10_CLEAR "0xFFFFFDFF"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT11_CLEAR "0xFFFFFBFF"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT12_CLEAR "0xFFFFF7FF"	//From file: cncmotions_specifications.pup2
#define DOUTPORT_DOUT13_CLEAR "0xFFFFEFFF"	//From file: cncmotions_specifications.pup2
#define ANALOG_USER_INPUT "0"	//From file: cncmotions_specifications.pup2
#define ANALOG_VELOCITY_COMMAND "1"	//From file: cncmotions_specifications.pup2
#define ANALOG_CURRENT_COMMAND "2"	//From file: cncmotions_specifications.pup2
#define ANALOG_FORCE_FEEDBACK "3"	//From file: cncmotions_specifications.pup2
#define ANALOG_FORCE_COMMAND "4"	//From file: cncmotions_specifications.pup2
#define ANALOG_JOYSTICK_INPUT "5"	//From file: cncmotions_specifications.pup2
#define ANALOG_TORQUE_COMP_INPUT "6"	//From file: cncmotions_specifications.pup2
#define ANALOG_INPUT_REVERSE_TORQUE_LIMIT "7"	//From file: cncmotions_specifications.pup2
#define ANALOG_INPUT_FORWARD_TORQUE_LIMIT "8"	//From file: cncmotions_specifications.pup2
#define ANALOG_INPUT_TACHO_FEEDBACK "9"	//From file: cncmotions_specifications.pup2
#define ANALOG_INPUT_POSITION_FEEDBACK "10"	//From file: cncmotions_specifications.pup2
#define EVENT_TYPE_SINGLE "0"	//From file: cncmotions_specifications.pup2
#define EVENT_TYPE_BY_GAP "1"	//From file: cncmotions_specifications.pup2
#define EVENT_TYPE_TABLE "2"	//From file: cncmotions_specifications.pup2
#define EVENT_TYPE_TABLE_HARDWARE "3"	//From file: cncmotions_specifications.pup2
#define EVENT_TYPE_TRIG_NOW "4"	//From file: cncmotions_specifications.pup2
#define EVENT_TYPE_MAX "4"	//From file: cncmotions_specifications.pup2
#define CON_FLT_ABORT "1001"	//From file: cncmotions_specifications.pup2
#define CON_FLT_SHORT "1002"	//From file: cncmotions_specifications.pup2
#define CON_FLT_ENCODER_ERROR "1003"	//From file: cncmotions_specifications.pup2
#define CON_FLT_WATCH_DOG "1004"	//From file: cncmotions_specifications.pup2
#define CON_FLT_DEAD_TIME "1005"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HALLS_DISCONNECTED "1006"	//From file: cncmotions_specifications.pup2
#define CON_FLT_MOTOR_STUCK "1007"	//From file: cncmotions_specifications.pup2
#define CON_FLT_BUS_OVER_VOLTAGE "1008"	//From file: cncmotions_specifications.pup2
#define CON_FLT_BUS_UNDER_VOLTAGE "1009"	//From file: cncmotions_specifications.pup2
#define CON_FLT_LOGIC_OVER_VOLTAGE "1010"	//From file: cncmotions_specifications.pup2
#define CON_FLT_LOGIC_UNDER_VOLTAGE "1011"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_BUS_CURRENT "1012"	//From file: cncmotions_specifications.pup2
#define CON_FLT_PHASE_A_CURRENT "1013"	//From file: cncmotions_specifications.pup2
#define CON_FLT_PHASE_B_CURRENT "1014"	//From file: cncmotions_specifications.pup2
#define CON_FLT_PHASE_C_CURRENT "1015"	//From file: cncmotions_specifications.pup2
#define CON_FLT_MOTOR_CURRENT "1016"	//From file: cncmotions_specifications.pup2
#define CON_FLT_OVER_DRIVER_POWER "1017"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_IPM_TEMP "1018"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_VELOCITY "1019"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_POS_ERR "1020"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_VEL_ERR "1021"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_CPU_TEMP "1022"	//From file: cncmotions_specifications.pup2
#define CON_FLT_BUS_OVER_VOLTAGE_ABS "1023"	//From file: cncmotions_specifications.pup2
#define CON_FLT_STO1 "1024"	//From file: cncmotions_specifications.pup2
#define CON_FLT_OVERCURR_A "1025"	//From file: cncmotions_specifications.pup2
#define CON_FLT_AUX_ENC_ERROR "1026"	//From file: cncmotions_specifications.pup2
#define CON_FLT_IPM_FAULT "1027"	//From file: cncmotions_specifications.pup2
#define CON_FLT_UNKNOWN_ENCODER_TYPE "1028"	//From file: cncmotions_specifications.pup2
#define CON_FLT_UNKNOWN_AUX_ENCODER_TYPE "1029"	//From file: cncmotions_specifications.pup2
#define CON_FLT_ECAM_MASTER_TOO_FAST "1030"	//From file: cncmotions_specifications.pup2
#define CON_FLT_FIFO_TOO_SMALL_ACCLERATION "1031"	//From file: cncmotions_specifications.pup2
#define CON_FLT_IMPROPER_MODULUS_USAGE "1032"	//From file: cncmotions_specifications.pup2
#define CON_FLT_BIT_FAILED "1033"	//From file: cncmotions_specifications.pup2
#define CON_FLT_STO2_OR_VCC_DRIVE "1034"	//From file: cncmotions_specifications.pup2
#define CON_FLT_CONTROL_AC_POWER_CUTOFF "1035"	//From file: cncmotions_specifications.pup2
#define CON_FLT_OVERCURR_B "1036"	//From file: cncmotions_specifications.pup2
#define CON_FLT_LINEAR_AMPLIFIER_OVER_CURR_CONT "1037"	//From file: cncmotions_specifications.pup2
#define CON_FLT_LINEAR_AMPLIFIER_OVER_VOLTAGE "1038"	//From file: cncmotions_specifications.pup2
#define CON_FLT_LINEAR_PWM_AMPLIFIER_CONFLICT "1039"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_MOTOR_TEMP "1040"	//From file: cncmotions_specifications.pup2
#define CON_FLT_RESERVED1 "1041"	//From file: cncmotions_specifications.pup2
#define CON_FLT_5V_ISO "1042"	//From file: cncmotions_specifications.pup2
#define CON_FLT_CI_DISCONNECTED "1043"	//From file: cncmotions_specifications.pup2
#define CON_FLT_MOTOR_I2T "1044"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_FORCE_ERR "1045"	//From file: cncmotions_specifications.pup2
#define CON_FLT_NO_FORCE_FEEDBACK "1046"	//From file: cncmotions_specifications.pup2
#define CON_FLT_5V_FAULT "1047"	//From file: cncmotions_specifications.pup2
#define CON_FLT_MEMBER_UNEXPECTED_MOTOR_OFF "1048"	//From file: cncmotions_specifications.pup2
#define CON_FLT_DUAL_STUCK "1049"	//From file: cncmotions_specifications.pup2
#define CON_FLT_FAULT_INPUT "1050"	//From file: cncmotions_specifications.pup2
#define CON_FLT_INRUSH_RESISTOR "1051"	//From file: cncmotions_specifications.pup2
#define CON_FLT_STO2 "1052"	//From file: cncmotions_specifications.pup2
#define CON_FLT_AMP_TYPE_ERROR "1053"	//From file: cncmotions_specifications.pup2
#define CON_FLT_MOTOR_AC_POWER_CUTOFF "1054"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_POS_ERR_OL "1055"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_VEL_ERR_OL "1056"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_FORCE_ERR_OL "1057"	//From file: cncmotions_specifications.pup2
#define CON_FLT_UNDERVOLTAGE "1058"	//From file: cncmotions_specifications.pup2
#define CON_FLT_OVERCURR_C "1059"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_BOARD_TEMP "1060"	//From file: cncmotions_specifications.pup2
#define CON_FLT_GANTRY_MEMBER_UNEXPECTED_MOTOR_OFF "1061"	//From file: cncmotions_specifications.pup2
#define CON_FLT_FAULT_INPUT_CONTROLLED_STOP "1062"	//From file: cncmotions_specifications.pup2
#define CON_FLT_VEC_MEMBER_UNEXPECTED_MOTOR_OFF "1063"	//From file: cncmotions_specifications.pup2
#define CON_FLT_ICNQC_ERROR "1064"	//From file: cncmotions_specifications.pup2
#define CON_FLT_STALL_DETECTED_AND_MOTOR_OFF "1065"	//From file: cncmotions_specifications.pup2
#define CON_FLT_VENC_MAX_NUM_PULSES_EXCEEDED "1066"	//From file: cncmotions_specifications.pup2
#define CON_FLT_ANOMALY_DETECTED "1067"	//From file: cncmotions_specifications.pup2
#define CON_FLT_ABS_ENC_ERROR "1068"	//From file: cncmotions_specifications.pup2
#define CON_FLT_ABS_ENC_CRC_ERR "1069"	//From file: cncmotions_specifications.pup2
#define CON_FLT_ABS_ENC_DISCONNECT "1070"	//From file: cncmotions_specifications.pup2
#define CON_FLT_UNSTABLE_CURR_LOOP_DETECTED "1071"	//From file: cncmotions_specifications.pup2
#define CON_FLT_HIGH_PIV_NOISE_DETECTED "1072"	//From file: cncmotions_specifications.pup2
#define CON_FLT_NO_PHASING_IS_DETECTED "1080"	//From file: cncmotions_specifications.pup2
#define CON_FLT_CPU_BG_WATCHDOG "1081"	//From file: cncmotions_specifications.pup2
#define MOTION_MODE_JOG "0"	//From file: cncmotions_specifications.pup2
#define MOTION_MODE_PTP "1"	//From file: cncmotions_specifications.pup2
#define MOTION_MODE_PTP_REP "2"	//From file: cncmotions_specifications.pup2
#define MOTION_MODE_CNCA "11"	//From file: cncmotions_specifications.pup2
#define MOTION_STATUS "7"	//From file: cncmotions_specifications.pup2
#define MOTION_END "0"	//From file: cncmotions_specifications.pup2
#define MOTOR_OFF "0"	//From file: cncmotions_specifications.pup2
#define MOTOR_ON "1"	//From file: cncmotions_specifications.pup2
#define A_AXIS "0"	//From file: uplmotion.pup2
#define B_AXIS "1"	//From file: uplmotion.pup2
#define C_AXIS "2"	//From file: uplmotion.pup2
#define D_AXIS "3"	//From file: uplmotion.pup2
#define E_AXIS "4"	//From file: uplmotion.pup2
#define F_AXIS "5"	//From file: uplmotion.pup2
#define G_AXIS "6"	//From file: uplmotion.pup2
#define H_AXIS "7"	//From file: uplmotion.pup2
#define USER_INPUT "0"	//From file: uplmotion.pup2
#define DEDICATED_HW_FUNCTION "1"	//From file: uplmotion.pup2
#define MOTOR_ON_INPUT "2"	//From file: uplmotion.pup2
#define BEGIN_MOTION "3"	//From file: uplmotion.pup2
#define STOP_MOTION "4"	//From file: uplmotion.pup2
#define CLEAR_IN_PULSES "5"	//From file: uplmotion.pup2
#define ABORT_RESUME_MOTION "6"	//From file: uplmotion.pup2
#define ALARM_RESET "7"	//From file: uplmotion.pup2
#define ABORT_MOTION "8"	//From file: uplmotion.pup2
#define REV_LIMIT "9"	//From file: uplmotion.pup2
#define FWD_LIMIT "10"	//From file: uplmotion.pup2
#define TORQUE_LIMIT_ON "11"	//From file: uplmotion.pup2
#define ACTIVATE_DYNAMIC_BRAKE "12"	//From file: uplmotion.pup2
#define LOCK_STATIC_BRAKE "13"	//From file: uplmotion.pup2
#define CONTROL_SET_CHANGE "14"	//From file: uplmotion.pup2
#define ADD_FILTER "15"	//From file: uplmotion.pup2
#define MODE_SWITCH_VEL_POS "16"	//From file: uplmotion.pup2
#define MODE_SWITCH_VEL_CUR "17"	//From file: uplmotion.pup2
#define MODE_SWITCH_POS_CUR "18"	//From file: uplmotion.pup2
#define CLEAR_ABS_ENC "19"	//From file: uplmotion.pup2
#define CHANGE_SPEED "20"	//From file: uplmotion.pup2
#define HOME "21"	//From file: uplmotion.pup2
#define MODE_SWITCH_POS_FORCE "22"	//From file: uplmotion.pup2
#define HALL_A "23"	//From file: uplmotion.pup2
#define FAULT_INPUT "24"	//From file: uplmotion.pup2
#define HOMING_ON_INPUT "25"	//From file: uplmotion.pup2
#define FAULT_INPUT_CONTROLLED_STOP "26"	//From file: uplmotion.pup2
#define HEIDENHAIN_LIMITS "27"	//From file: uplmotion.pup2
#define DOUT_USER_OUTPUT "0"	//From file: uplmotion.pup2
#define DOUT_DEDICATED_HW_FUNCTION "1"	//From file: uplmotion.pup2
#define DOUT_MOTOR_ON "2"	//From file: uplmotion.pup2
#define DOUT_IN_MOTION "3"	//From file: uplmotion.pup2
#define DOUT_IN_ACCELERATION "4"	//From file: uplmotion.pup2
#define DOUT_IN_DECELERATION "5"	//From file: uplmotion.pup2
#define DOUT_IN_CONSTANT_SPEED "6"	//From file: uplmotion.pup2
#define DOUT_END_OF_MOTION "7"	//From file: uplmotion.pup2
#define DOUT_IN_TARGET "8"	//From file: uplmotion.pup2
#define DOUT_ALARM "9"	//From file: uplmotion.pup2
#define DOUT_WARNINGS_IN_LAST_MOTION "10"	//From file: uplmotion.pup2
#define DOUT_SATURATIONS_IN_LAST_MOTION "11"	//From file: uplmotion.pup2
#define DOUT_RLS_FLS_ACTIVE "12"	//From file: uplmotion.pup2
#define DOUT_OUT_OF_TRAVEL "13"	//From file: uplmotion.pup2
#define DOUT_REGENERATION_ACTIVE "14"	//From file: uplmotion.pup2
#define DOUT_DYNAMIC_BRAKE_ACTIVE "15"	//From file: uplmotion.pup2
#define DOUT_STATIC_BRAKE_LOCK "16"	//From file: uplmotion.pup2
#define DOUT_STATIC_UNUSED "17"	//From file: uplmotion.pup2
#define DOUT_RLS_ACTIVE "18"	//From file: uplmotion.pup2
#define DOUT_FLS_ACTIVE "19"	//From file: uplmotion.pup2
#define DOUT_HOMING_STAT "20"	//From file: uplmotion.pup2
#define DOUT_FORCE_IN_TARGET "21"	//From file: uplmotion.pup2
#define MAX_OUTPUT_MODE "21"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT1_BIT "0x00000001"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT2_BIT "0x00000002"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT3_BIT "0x00000004"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT4_BIT "0x00000008"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT5_BIT "0x00000010"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT6_BIT "0x00000020"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT7_BIT "0x00000040"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT8_BIT "0x00000080"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT9_BIT "0x00000100"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT10_BIT "0x00000200"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT11_BIT "0x00000400"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT12_BIT "0x00000800"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT13_BIT "0x00001000"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT1_SET "0x00000001"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT2_SET "0x00000002"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT3_SET "0x00000004"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT4_SET "0x00000008"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT5_SET "0x00000010"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT6_SET "0x00000020"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT7_SET "0x00000040"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT8_SET "0x00000080"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT9_SET "0x00000100"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT10_SET "0x00000200"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT11_SET "0x00000400"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT12_SET "0x00000800"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT13_SET "0x00001000"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT1_CLEAR "0xFFFFFFFE"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT2_CLEAR "0xFFFFFFFD"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT3_CLEAR "0xFFFFFFFB"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT4_CLEAR "0xFFFFFFF7"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT5_CLEAR "0xFFFFFFEF"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT6_CLEAR "0xFFFFFFDF"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT7_CLEAR "0xFFFFFFBF"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT8_CLEAR "0xFFFFFF7F"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT9_CLEAR "0xFFFFFEFF"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT10_CLEAR "0xFFFFFDFF"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT11_CLEAR "0xFFFFFBFF"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT12_CLEAR "0xFFFFF7FF"	//From file: uplmotion.pup2
#define DOUTPORT_DOUT13_CLEAR "0xFFFFEFFF"	//From file: uplmotion.pup2
#define ANALOG_USER_INPUT "0"	//From file: uplmotion.pup2
#define ANALOG_VELOCITY_COMMAND "1"	//From file: uplmotion.pup2
#define ANALOG_CURRENT_COMMAND "2"	//From file: uplmotion.pup2
#define ANALOG_FORCE_FEEDBACK "3"	//From file: uplmotion.pup2
#define ANALOG_FORCE_COMMAND "4"	//From file: uplmotion.pup2
#define ANALOG_JOYSTICK_INPUT "5"	//From file: uplmotion.pup2
#define ANALOG_TORQUE_COMP_INPUT "6"	//From file: uplmotion.pup2
#define ANALOG_INPUT_REVERSE_TORQUE_LIMIT "7"	//From file: uplmotion.pup2
#define ANALOG_INPUT_FORWARD_TORQUE_LIMIT "8"	//From file: uplmotion.pup2
#define ANALOG_INPUT_TACHO_FEEDBACK "9"	//From file: uplmotion.pup2
#define ANALOG_INPUT_POSITION_FEEDBACK "10"	//From file: uplmotion.pup2
#define EVENT_TYPE_SINGLE "0"	//From file: uplmotion.pup2
#define EVENT_TYPE_BY_GAP "1"	//From file: uplmotion.pup2
#define EVENT_TYPE_TABLE "2"	//From file: uplmotion.pup2
#define EVENT_TYPE_TABLE_HARDWARE "3"	//From file: uplmotion.pup2
#define EVENT_TYPE_TRIG_NOW "4"	//From file: uplmotion.pup2
#define EVENT_TYPE_MAX "4"	//From file: uplmotion.pup2
#define CON_FLT_ABORT "1001"	//From file: uplmotion.pup2
#define CON_FLT_SHORT "1002"	//From file: uplmotion.pup2
#define CON_FLT_ENCODER_ERROR "1003"	//From file: uplmotion.pup2
#define CON_FLT_WATCH_DOG "1004"	//From file: uplmotion.pup2
#define CON_FLT_DEAD_TIME "1005"	//From file: uplmotion.pup2
#define CON_FLT_HALLS_DISCONNECTED "1006"	//From file: uplmotion.pup2
#define CON_FLT_MOTOR_STUCK "1007"	//From file: uplmotion.pup2
#define CON_FLT_BUS_OVER_VOLTAGE "1008"	//From file: uplmotion.pup2
#define CON_FLT_BUS_UNDER_VOLTAGE "1009"	//From file: uplmotion.pup2
#define CON_FLT_LOGIC_OVER_VOLTAGE "1010"	//From file: uplmotion.pup2
#define CON_FLT_LOGIC_UNDER_VOLTAGE "1011"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_BUS_CURRENT "1012"	//From file: uplmotion.pup2
#define CON_FLT_PHASE_A_CURRENT "1013"	//From file: uplmotion.pup2
#define CON_FLT_PHASE_B_CURRENT "1014"	//From file: uplmotion.pup2
#define CON_FLT_PHASE_C_CURRENT "1015"	//From file: uplmotion.pup2
#define CON_FLT_MOTOR_CURRENT "1016"	//From file: uplmotion.pup2
#define CON_FLT_OVER_DRIVER_POWER "1017"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_IPM_TEMP "1018"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_VELOCITY "1019"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_POS_ERR "1020"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_VEL_ERR "1021"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_CPU_TEMP "1022"	//From file: uplmotion.pup2
#define CON_FLT_BUS_OVER_VOLTAGE_ABS "1023"	//From file: uplmotion.pup2
#define CON_FLT_STO1 "1024"	//From file: uplmotion.pup2
#define CON_FLT_OVERCURR_A "1025"	//From file: uplmotion.pup2
#define CON_FLT_AUX_ENC_ERROR "1026"	//From file: uplmotion.pup2
#define CON_FLT_IPM_FAULT "1027"	//From file: uplmotion.pup2
#define CON_FLT_UNKNOWN_ENCODER_TYPE "1028"	//From file: uplmotion.pup2
#define CON_FLT_UNKNOWN_AUX_ENCODER_TYPE "1029"	//From file: uplmotion.pup2
#define CON_FLT_ECAM_MASTER_TOO_FAST "1030"	//From file: uplmotion.pup2
#define CON_FLT_FIFO_TOO_SMALL_ACCLERATION "1031"	//From file: uplmotion.pup2
#define CON_FLT_IMPROPER_MODULUS_USAGE "1032"	//From file: uplmotion.pup2
#define CON_FLT_BIT_FAILED "1033"	//From file: uplmotion.pup2
#define CON_FLT_STO2_OR_VCC_DRIVE "1034"	//From file: uplmotion.pup2
#define CON_FLT_CONTROL_AC_POWER_CUTOFF "1035"	//From file: uplmotion.pup2
#define CON_FLT_OVERCURR_B "1036"	//From file: uplmotion.pup2
#define CON_FLT_LINEAR_AMPLIFIER_OVER_CURR_CONT "1037"	//From file: uplmotion.pup2
#define CON_FLT_LINEAR_AMPLIFIER_OVER_VOLTAGE "1038"	//From file: uplmotion.pup2
#define CON_FLT_LINEAR_PWM_AMPLIFIER_CONFLICT "1039"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_MOTOR_TEMP "1040"	//From file: uplmotion.pup2
#define CON_FLT_RESERVED1 "1041"	//From file: uplmotion.pup2
#define CON_FLT_5V_ISO "1042"	//From file: uplmotion.pup2
#define CON_FLT_CI_DISCONNECTED "1043"	//From file: uplmotion.pup2
#define CON_FLT_MOTOR_I2T "1044"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_FORCE_ERR "1045"	//From file: uplmotion.pup2
#define CON_FLT_NO_FORCE_FEEDBACK "1046"	//From file: uplmotion.pup2
#define CON_FLT_5V_FAULT "1047"	//From file: uplmotion.pup2
#define CON_FLT_MEMBER_UNEXPECTED_MOTOR_OFF "1048"	//From file: uplmotion.pup2
#define CON_FLT_DUAL_STUCK "1049"	//From file: uplmotion.pup2
#define CON_FLT_FAULT_INPUT "1050"	//From file: uplmotion.pup2
#define CON_FLT_INRUSH_RESISTOR "1051"	//From file: uplmotion.pup2
#define CON_FLT_STO2 "1052"	//From file: uplmotion.pup2
#define CON_FLT_AMP_TYPE_ERROR "1053"	//From file: uplmotion.pup2
#define CON_FLT_MOTOR_AC_POWER_CUTOFF "1054"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_POS_ERR_OL "1055"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_VEL_ERR_OL "1056"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_FORCE_ERR_OL "1057"	//From file: uplmotion.pup2
#define CON_FLT_UNDERVOLTAGE "1058"	//From file: uplmotion.pup2
#define CON_FLT_OVERCURR_C "1059"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_BOARD_TEMP "1060"	//From file: uplmotion.pup2
#define CON_FLT_GANTRY_MEMBER_UNEXPECTED_MOTOR_OFF "1061"	//From file: uplmotion.pup2
#define CON_FLT_FAULT_INPUT_CONTROLLED_STOP "1062"	//From file: uplmotion.pup2
#define CON_FLT_VEC_MEMBER_UNEXPECTED_MOTOR_OFF "1063"	//From file: uplmotion.pup2
#define CON_FLT_ICNQC_ERROR "1064"	//From file: uplmotion.pup2
#define CON_FLT_STALL_DETECTED_AND_MOTOR_OFF "1065"	//From file: uplmotion.pup2
#define CON_FLT_VENC_MAX_NUM_PULSES_EXCEEDED "1066"	//From file: uplmotion.pup2
#define CON_FLT_ANOMALY_DETECTED "1067"	//From file: uplmotion.pup2
#define CON_FLT_ABS_ENC_ERROR "1068"	//From file: uplmotion.pup2
#define CON_FLT_ABS_ENC_CRC_ERR "1069"	//From file: uplmotion.pup2
#define CON_FLT_ABS_ENC_DISCONNECT "1070"	//From file: uplmotion.pup2
#define CON_FLT_UNSTABLE_CURR_LOOP_DETECTED "1071"	//From file: uplmotion.pup2
#define CON_FLT_HIGH_PIV_NOISE_DETECTED "1072"	//From file: uplmotion.pup2
#define CON_FLT_NO_PHASING_IS_DETECTED "1080"	//From file: uplmotion.pup2
#define CON_FLT_CPU_BG_WATCHDOG "1081"	//From file: uplmotion.pup2
#define MOTION_MODE_JOG "0"	//From file: uplmotion.pup2
#define MOTION_MODE_PTP "1"	//From file: uplmotion.pup2
#define MOTION_MODE_PTP_REP "2"	//From file: uplmotion.pup2
#define MOTION_MODE_CNCA "11"	//From file: uplmotion.pup2
#define MOTION_STATUS "7"	//From file: uplmotion.pup2
#define MOTION_END "0"	//From file: uplmotion.pup2
#define MOTOR_OFF "0"	//From file: uplmotion.pup2
#define MOTOR_ON "1"	//From file: uplmotion.pup2
#define A_AXIS "0"	//From file: uplutility.pup2
#define B_AXIS "1"	//From file: uplutility.pup2
#define C_AXIS "2"	//From file: uplutility.pup2
#define D_AXIS "3"	//From file: uplutility.pup2
#define E_AXIS "4"	//From file: uplutility.pup2
#define F_AXIS "5"	//From file: uplutility.pup2
#define G_AXIS "6"	//From file: uplutility.pup2
#define H_AXIS "7"	//From file: uplutility.pup2
#define USER_INPUT "0"	//From file: uplutility.pup2
#define DEDICATED_HW_FUNCTION "1"	//From file: uplutility.pup2
#define MOTOR_ON_INPUT "2"	//From file: uplutility.pup2
#define BEGIN_MOTION "3"	//From file: uplutility.pup2
#define STOP_MOTION "4"	//From file: uplutility.pup2
#define CLEAR_IN_PULSES "5"	//From file: uplutility.pup2
#define ABORT_RESUME_MOTION "6"	//From file: uplutility.pup2
#define ALARM_RESET "7"	//From file: uplutility.pup2
#define ABORT_MOTION "8"	//From file: uplutility.pup2
#define REV_LIMIT "9"	//From file: uplutility.pup2
#define FWD_LIMIT "10"	//From file: uplutility.pup2
#define TORQUE_LIMIT_ON "11"	//From file: uplutility.pup2
#define ACTIVATE_DYNAMIC_BRAKE "12"	//From file: uplutility.pup2
#define LOCK_STATIC_BRAKE "13"	//From file: uplutility.pup2
#define CONTROL_SET_CHANGE "14"	//From file: uplutility.pup2
#define ADD_FILTER "15"	//From file: uplutility.pup2
#define MODE_SWITCH_VEL_POS "16"	//From file: uplutility.pup2
#define MODE_SWITCH_VEL_CUR "17"	//From file: uplutility.pup2
#define MODE_SWITCH_POS_CUR "18"	//From file: uplutility.pup2
#define CLEAR_ABS_ENC "19"	//From file: uplutility.pup2
#define CHANGE_SPEED "20"	//From file: uplutility.pup2
#define HOME "21"	//From file: uplutility.pup2
#define MODE_SWITCH_POS_FORCE "22"	//From file: uplutility.pup2
#define HALL_A "23"	//From file: uplutility.pup2
#define FAULT_INPUT "24"	//From file: uplutility.pup2
#define HOMING_ON_INPUT "25"	//From file: uplutility.pup2
#define FAULT_INPUT_CONTROLLED_STOP "26"	//From file: uplutility.pup2
#define HEIDENHAIN_LIMITS "27"	//From file: uplutility.pup2
#define DOUT_USER_OUTPUT "0"	//From file: uplutility.pup2
#define DOUT_DEDICATED_HW_FUNCTION "1"	//From file: uplutility.pup2
#define DOUT_MOTOR_ON "2"	//From file: uplutility.pup2
#define DOUT_IN_MOTION "3"	//From file: uplutility.pup2
#define DOUT_IN_ACCELERATION "4"	//From file: uplutility.pup2
#define DOUT_IN_DECELERATION "5"	//From file: uplutility.pup2
#define DOUT_IN_CONSTANT_SPEED "6"	//From file: uplutility.pup2
#define DOUT_END_OF_MOTION "7"	//From file: uplutility.pup2
#define DOUT_IN_TARGET "8"	//From file: uplutility.pup2
#define DOUT_ALARM "9"	//From file: uplutility.pup2
#define DOUT_WARNINGS_IN_LAST_MOTION "10"	//From file: uplutility.pup2
#define DOUT_SATURATIONS_IN_LAST_MOTION "11"	//From file: uplutility.pup2
#define DOUT_RLS_FLS_ACTIVE "12"	//From file: uplutility.pup2
#define DOUT_OUT_OF_TRAVEL "13"	//From file: uplutility.pup2
#define DOUT_REGENERATION_ACTIVE "14"	//From file: uplutility.pup2
#define DOUT_DYNAMIC_BRAKE_ACTIVE "15"	//From file: uplutility.pup2
#define DOUT_STATIC_BRAKE_LOCK "16"	//From file: uplutility.pup2
#define DOUT_STATIC_UNUSED "17"	//From file: uplutility.pup2
#define DOUT_RLS_ACTIVE "18"	//From file: uplutility.pup2
#define DOUT_FLS_ACTIVE "19"	//From file: uplutility.pup2
#define DOUT_HOMING_STAT "20"	//From file: uplutility.pup2
#define DOUT_FORCE_IN_TARGET "21"	//From file: uplutility.pup2
#define MAX_OUTPUT_MODE "21"	//From file: uplutility.pup2
#define DOUTPORT_DOUT1_BIT "0x00000001"	//From file: uplutility.pup2
#define DOUTPORT_DOUT2_BIT "0x00000002"	//From file: uplutility.pup2
#define DOUTPORT_DOUT3_BIT "0x00000004"	//From file: uplutility.pup2
#define DOUTPORT_DOUT4_BIT "0x00000008"	//From file: uplutility.pup2
#define DOUTPORT_DOUT5_BIT "0x00000010"	//From file: uplutility.pup2
#define DOUTPORT_DOUT6_BIT "0x00000020"	//From file: uplutility.pup2
#define DOUTPORT_DOUT7_BIT "0x00000040"	//From file: uplutility.pup2
#define DOUTPORT_DOUT8_BIT "0x00000080"	//From file: uplutility.pup2
#define DOUTPORT_DOUT9_BIT "0x00000100"	//From file: uplutility.pup2
#define DOUTPORT_DOUT10_BIT "0x00000200"	//From file: uplutility.pup2
#define DOUTPORT_DOUT11_BIT "0x00000400"	//From file: uplutility.pup2
#define DOUTPORT_DOUT12_BIT "0x00000800"	//From file: uplutility.pup2
#define DOUTPORT_DOUT13_BIT "0x00001000"	//From file: uplutility.pup2
#define DOUTPORT_DOUT1_SET "0x00000001"	//From file: uplutility.pup2
#define DOUTPORT_DOUT2_SET "0x00000002"	//From file: uplutility.pup2
#define DOUTPORT_DOUT3_SET "0x00000004"	//From file: uplutility.pup2
#define DOUTPORT_DOUT4_SET "0x00000008"	//From file: uplutility.pup2
#define DOUTPORT_DOUT5_SET "0x00000010"	//From file: uplutility.pup2
#define DOUTPORT_DOUT6_SET "0x00000020"	//From file: uplutility.pup2
#define DOUTPORT_DOUT7_SET "0x00000040"	//From file: uplutility.pup2
#define DOUTPORT_DOUT8_SET "0x00000080"	//From file: uplutility.pup2
#define DOUTPORT_DOUT9_SET "0x00000100"	//From file: uplutility.pup2
#define DOUTPORT_DOUT10_SET "0x00000200"	//From file: uplutility.pup2
#define DOUTPORT_DOUT11_SET "0x00000400"	//From file: uplutility.pup2
#define DOUTPORT_DOUT12_SET "0x00000800"	//From file: uplutility.pup2
#define DOUTPORT_DOUT13_SET "0x00001000"	//From file: uplutility.pup2
#define DOUTPORT_DOUT1_CLEAR "0xFFFFFFFE"	//From file: uplutility.pup2
#define DOUTPORT_DOUT2_CLEAR "0xFFFFFFFD"	//From file: uplutility.pup2
#define DOUTPORT_DOUT3_CLEAR "0xFFFFFFFB"	//From file: uplutility.pup2
#define DOUTPORT_DOUT4_CLEAR "0xFFFFFFF7"	//From file: uplutility.pup2
#define DOUTPORT_DOUT5_CLEAR "0xFFFFFFEF"	//From file: uplutility.pup2
#define DOUTPORT_DOUT6_CLEAR "0xFFFFFFDF"	//From file: uplutility.pup2
#define DOUTPORT_DOUT7_CLEAR "0xFFFFFFBF"	//From file: uplutility.pup2
#define DOUTPORT_DOUT8_CLEAR "0xFFFFFF7F"	//From file: uplutility.pup2
#define DOUTPORT_DOUT9_CLEAR "0xFFFFFEFF"	//From file: uplutility.pup2
#define DOUTPORT_DOUT10_CLEAR "0xFFFFFDFF"	//From file: uplutility.pup2
#define DOUTPORT_DOUT11_CLEAR "0xFFFFFBFF"	//From file: uplutility.pup2
#define DOUTPORT_DOUT12_CLEAR "0xFFFFF7FF"	//From file: uplutility.pup2
#define DOUTPORT_DOUT13_CLEAR "0xFFFFEFFF"	//From file: uplutility.pup2
#define ANALOG_USER_INPUT "0"	//From file: uplutility.pup2
#define ANALOG_VELOCITY_COMMAND "1"	//From file: uplutility.pup2
#define ANALOG_CURRENT_COMMAND "2"	//From file: uplutility.pup2
#define ANALOG_FORCE_FEEDBACK "3"	//From file: uplutility.pup2
#define ANALOG_FORCE_COMMAND "4"	//From file: uplutility.pup2
#define ANALOG_JOYSTICK_INPUT "5"	//From file: uplutility.pup2
#define ANALOG_TORQUE_COMP_INPUT "6"	//From file: uplutility.pup2
#define ANALOG_INPUT_REVERSE_TORQUE_LIMIT "7"	//From file: uplutility.pup2
#define ANALOG_INPUT_FORWARD_TORQUE_LIMIT "8"	//From file: uplutility.pup2
#define ANALOG_INPUT_TACHO_FEEDBACK "9"	//From file: uplutility.pup2
#define ANALOG_INPUT_POSITION_FEEDBACK "10"	//From file: uplutility.pup2
#define EVENT_TYPE_SINGLE "0"	//From file: uplutility.pup2
#define EVENT_TYPE_BY_GAP "1"	//From file: uplutility.pup2
#define EVENT_TYPE_TABLE "2"	//From file: uplutility.pup2
#define EVENT_TYPE_TABLE_HARDWARE "3"	//From file: uplutility.pup2
#define EVENT_TYPE_TRIG_NOW "4"	//From file: uplutility.pup2
#define EVENT_TYPE_MAX "4"	//From file: uplutility.pup2
#define CON_FLT_ABORT "1001"	//From file: uplutility.pup2
#define CON_FLT_SHORT "1002"	//From file: uplutility.pup2
#define CON_FLT_ENCODER_ERROR "1003"	//From file: uplutility.pup2
#define CON_FLT_WATCH_DOG "1004"	//From file: uplutility.pup2
#define CON_FLT_DEAD_TIME "1005"	//From file: uplutility.pup2
#define CON_FLT_HALLS_DISCONNECTED "1006"	//From file: uplutility.pup2
#define CON_FLT_MOTOR_STUCK "1007"	//From file: uplutility.pup2
#define CON_FLT_BUS_OVER_VOLTAGE "1008"	//From file: uplutility.pup2
#define CON_FLT_BUS_UNDER_VOLTAGE "1009"	//From file: uplutility.pup2
#define CON_FLT_LOGIC_OVER_VOLTAGE "1010"	//From file: uplutility.pup2
#define CON_FLT_LOGIC_UNDER_VOLTAGE "1011"	//From file: uplutility.pup2
#define CON_FLT_HIGH_BUS_CURRENT "1012"	//From file: uplutility.pup2
#define CON_FLT_PHASE_A_CURRENT "1013"	//From file: uplutility.pup2
#define CON_FLT_PHASE_B_CURRENT "1014"	//From file: uplutility.pup2
#define CON_FLT_PHASE_C_CURRENT "1015"	//From file: uplutility.pup2
#define CON_FLT_MOTOR_CURRENT "1016"	//From file: uplutility.pup2
#define CON_FLT_OVER_DRIVER_POWER "1017"	//From file: uplutility.pup2
#define CON_FLT_HIGH_IPM_TEMP "1018"	//From file: uplutility.pup2
#define CON_FLT_HIGH_VELOCITY "1019"	//From file: uplutility.pup2
#define CON_FLT_HIGH_POS_ERR "1020"	//From file: uplutility.pup2
#define CON_FLT_HIGH_VEL_ERR "1021"	//From file: uplutility.pup2
#define CON_FLT_HIGH_CPU_TEMP "1022"	//From file: uplutility.pup2
#define CON_FLT_BUS_OVER_VOLTAGE_ABS "1023"	//From file: uplutility.pup2
#define CON_FLT_STO1 "1024"	//From file: uplutility.pup2
#define CON_FLT_OVERCURR_A "1025"	//From file: uplutility.pup2
#define CON_FLT_AUX_ENC_ERROR "1026"	//From file: uplutility.pup2
#define CON_FLT_IPM_FAULT "1027"	//From file: uplutility.pup2
#define CON_FLT_UNKNOWN_ENCODER_TYPE "1028"	//From file: uplutility.pup2
#define CON_FLT_UNKNOWN_AUX_ENCODER_TYPE "1029"	//From file: uplutility.pup2
#define CON_FLT_ECAM_MASTER_TOO_FAST "1030"	//From file: uplutility.pup2
#define CON_FLT_FIFO_TOO_SMALL_ACCLERATION "1031"	//From file: uplutility.pup2
#define CON_FLT_IMPROPER_MODULUS_USAGE "1032"	//From file: uplutility.pup2
#define CON_FLT_BIT_FAILED "1033"	//From file: uplutility.pup2
#define CON_FLT_STO2_OR_VCC_DRIVE "1034"	//From file: uplutility.pup2
#define CON_FLT_CONTROL_AC_POWER_CUTOFF "1035"	//From file: uplutility.pup2
#define CON_FLT_OVERCURR_B "1036"	//From file: uplutility.pup2
#define CON_FLT_LINEAR_AMPLIFIER_OVER_CURR_CONT "1037"	//From file: uplutility.pup2
#define CON_FLT_LINEAR_AMPLIFIER_OVER_VOLTAGE "1038"	//From file: uplutility.pup2
#define CON_FLT_LINEAR_PWM_AMPLIFIER_CONFLICT "1039"	//From file: uplutility.pup2
#define CON_FLT_HIGH_MOTOR_TEMP "1040"	//From file: uplutility.pup2
#define CON_FLT_RESERVED1 "1041"	//From file: uplutility.pup2
#define CON_FLT_5V_ISO "1042"	//From file: uplutility.pup2
#define CON_FLT_CI_DISCONNECTED "1043"	//From file: uplutility.pup2
#define CON_FLT_MOTOR_I2T "1044"	//From file: uplutility.pup2
#define CON_FLT_HIGH_FORCE_ERR "1045"	//From file: uplutility.pup2
#define CON_FLT_NO_FORCE_FEEDBACK "1046"	//From file: uplutility.pup2
#define CON_FLT_5V_FAULT "1047"	//From file: uplutility.pup2
#define CON_FLT_MEMBER_UNEXPECTED_MOTOR_OFF "1048"	//From file: uplutility.pup2
#define CON_FLT_DUAL_STUCK "1049"	//From file: uplutility.pup2
#define CON_FLT_FAULT_INPUT "1050"	//From file: uplutility.pup2
#define CON_FLT_INRUSH_RESISTOR "1051"	//From file: uplutility.pup2
#define CON_FLT_STO2 "1052"	//From file: uplutility.pup2
#define CON_FLT_AMP_TYPE_ERROR "1053"	//From file: uplutility.pup2
#define CON_FLT_MOTOR_AC_POWER_CUTOFF "1054"	//From file: uplutility.pup2
#define CON_FLT_HIGH_POS_ERR_OL "1055"	//From file: uplutility.pup2
#define CON_FLT_HIGH_VEL_ERR_OL "1056"	//From file: uplutility.pup2
#define CON_FLT_HIGH_FORCE_ERR_OL "1057"	//From file: uplutility.pup2
#define CON_FLT_UNDERVOLTAGE "1058"	//From file: uplutility.pup2
#define CON_FLT_OVERCURR_C "1059"	//From file: uplutility.pup2
#define CON_FLT_HIGH_BOARD_TEMP "1060"	//From file: uplutility.pup2
#define CON_FLT_GANTRY_MEMBER_UNEXPECTED_MOTOR_OFF "1061"	//From file: uplutility.pup2
#define CON_FLT_FAULT_INPUT_CONTROLLED_STOP "1062"	//From file: uplutility.pup2
#define CON_FLT_VEC_MEMBER_UNEXPECTED_MOTOR_OFF "1063"	//From file: uplutility.pup2
#define CON_FLT_ICNQC_ERROR "1064"	//From file: uplutility.pup2
#define CON_FLT_STALL_DETECTED_AND_MOTOR_OFF "1065"	//From file: uplutility.pup2
#define CON_FLT_VENC_MAX_NUM_PULSES_EXCEEDED "1066"	//From file: uplutility.pup2
#define CON_FLT_ANOMALY_DETECTED "1067"	//From file: uplutility.pup2
#define CON_FLT_ABS_ENC_ERROR "1068"	//From file: uplutility.pup2
#define CON_FLT_ABS_ENC_CRC_ERR "1069"	//From file: uplutility.pup2
#define CON_FLT_ABS_ENC_DISCONNECT "1070"	//From file: uplutility.pup2
#define CON_FLT_UNSTABLE_CURR_LOOP_DETECTED "1071"	//From file: uplutility.pup2
#define CON_FLT_HIGH_PIV_NOISE_DETECTED "1072"	//From file: uplutility.pup2
#define CON_FLT_NO_PHASING_IS_DETECTED "1080"	//From file: uplutility.pup2
#define CON_FLT_CPU_BG_WATCHDOG "1081"	//From file: uplutility.pup2
#define MOTOR_OFF "0"	//From file: uplutility.pup2
#define MOTOR_ON "1"	//From file: uplutility.pup2
#define A_AXIS "0"	//From file: uplcnc.pup2
#define B_AXIS "1"	//From file: uplcnc.pup2
#define C_AXIS "2"	//From file: uplcnc.pup2
#define D_AXIS "3"	//From file: uplcnc.pup2
#define E_AXIS "4"	//From file: uplcnc.pup2
#define F_AXIS "5"	//From file: uplcnc.pup2
#define G_AXIS "6"	//From file: uplcnc.pup2
#define H_AXIS "7"	//From file: uplcnc.pup2
#define USER_INPUT "0"	//From file: uplcnc.pup2
#define DEDICATED_HW_FUNCTION "1"	//From file: uplcnc.pup2
#define MOTOR_ON_INPUT "2"	//From file: uplcnc.pup2
#define BEGIN_MOTION "3"	//From file: uplcnc.pup2
#define STOP_MOTION "4"	//From file: uplcnc.pup2
#define CLEAR_IN_PULSES "5"	//From file: uplcnc.pup2
#define ABORT_RESUME_MOTION "6"	//From file: uplcnc.pup2
#define ALARM_RESET "7"	//From file: uplcnc.pup2
#define ABORT_MOTION "8"	//From file: uplcnc.pup2
#define REV_LIMIT "9"	//From file: uplcnc.pup2
#define FWD_LIMIT "10"	//From file: uplcnc.pup2
#define TORQUE_LIMIT_ON "11"	//From file: uplcnc.pup2
#define ACTIVATE_DYNAMIC_BRAKE "12"	//From file: uplcnc.pup2
#define LOCK_STATIC_BRAKE "13"	//From file: uplcnc.pup2
#define CONTROL_SET_CHANGE "14"	//From file: uplcnc.pup2
#define ADD_FILTER "15"	//From file: uplcnc.pup2
#define MODE_SWITCH_VEL_POS "16"	//From file: uplcnc.pup2
#define MODE_SWITCH_VEL_CUR "17"	//From file: uplcnc.pup2
#define MODE_SWITCH_POS_CUR "18"	//From file: uplcnc.pup2
#define CLEAR_ABS_ENC "19"	//From file: uplcnc.pup2
#define CHANGE_SPEED "20"	//From file: uplcnc.pup2
#define HOME "21"	//From file: uplcnc.pup2
#define MODE_SWITCH_POS_FORCE "22"	//From file: uplcnc.pup2
#define HALL_A "23"	//From file: uplcnc.pup2
#define FAULT_INPUT "24"	//From file: uplcnc.pup2
#define HOMING_ON_INPUT "25"	//From file: uplcnc.pup2
#define FAULT_INPUT_CONTROLLED_STOP "26"	//From file: uplcnc.pup2
#define HEIDENHAIN_LIMITS "27"	//From file: uplcnc.pup2
#define DOUT_USER_OUTPUT "0"	//From file: uplcnc.pup2
#define DOUT_DEDICATED_HW_FUNCTION "1"	//From file: uplcnc.pup2
#define DOUT_MOTOR_ON "2"	//From file: uplcnc.pup2
#define DOUT_IN_MOTION "3"	//From file: uplcnc.pup2
#define DOUT_IN_ACCELERATION "4"	//From file: uplcnc.pup2
#define DOUT_IN_DECELERATION "5"	//From file: uplcnc.pup2
#define DOUT_IN_CONSTANT_SPEED "6"	//From file: uplcnc.pup2
#define DOUT_END_OF_MOTION "7"	//From file: uplcnc.pup2
#define DOUT_IN_TARGET "8"	//From file: uplcnc.pup2
#define DOUT_ALARM "9"	//From file: uplcnc.pup2
#define DOUT_WARNINGS_IN_LAST_MOTION "10"	//From file: uplcnc.pup2
#define DOUT_SATURATIONS_IN_LAST_MOTION "11"	//From file: uplcnc.pup2
#define DOUT_RLS_FLS_ACTIVE "12"	//From file: uplcnc.pup2
#define DOUT_OUT_OF_TRAVEL "13"	//From file: uplcnc.pup2
#define DOUT_REGENERATION_ACTIVE "14"	//From file: uplcnc.pup2
#define DOUT_DYNAMIC_BRAKE_ACTIVE "15"	//From file: uplcnc.pup2
#define DOUT_STATIC_BRAKE_LOCK "16"	//From file: uplcnc.pup2
#define DOUT_STATIC_UNUSED "17"	//From file: uplcnc.pup2
#define DOUT_RLS_ACTIVE "18"	//From file: uplcnc.pup2
#define DOUT_FLS_ACTIVE "19"	//From file: uplcnc.pup2
#define DOUT_HOMING_STAT "20"	//From file: uplcnc.pup2
#define DOUT_FORCE_IN_TARGET "21"	//From file: uplcnc.pup2
#define MAX_OUTPUT_MODE "21"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT1_BIT "0x00000001"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT2_BIT "0x00000002"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT3_BIT "0x00000004"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT4_BIT "0x00000008"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT5_BIT "0x00000010"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT6_BIT "0x00000020"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT7_BIT "0x00000040"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT8_BIT "0x00000080"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT9_BIT "0x00000100"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT10_BIT "0x00000200"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT11_BIT "0x00000400"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT12_BIT "0x00000800"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT13_BIT "0x00001000"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT1_SET "0x00000001"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT2_SET "0x00000002"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT3_SET "0x00000004"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT4_SET "0x00000008"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT5_SET "0x00000010"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT6_SET "0x00000020"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT7_SET "0x00000040"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT8_SET "0x00000080"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT9_SET "0x00000100"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT10_SET "0x00000200"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT11_SET "0x00000400"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT12_SET "0x00000800"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT13_SET "0x00001000"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT1_CLEAR "0xFFFFFFFE"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT2_CLEAR "0xFFFFFFFD"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT3_CLEAR "0xFFFFFFFB"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT4_CLEAR "0xFFFFFFF7"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT5_CLEAR "0xFFFFFFEF"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT6_CLEAR "0xFFFFFFDF"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT7_CLEAR "0xFFFFFFBF"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT8_CLEAR "0xFFFFFF7F"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT9_CLEAR "0xFFFFFEFF"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT10_CLEAR "0xFFFFFDFF"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT11_CLEAR "0xFFFFFBFF"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT12_CLEAR "0xFFFFF7FF"	//From file: uplcnc.pup2
#define DOUTPORT_DOUT13_CLEAR "0xFFFFEFFF"	//From file: uplcnc.pup2
#define ANALOG_USER_INPUT "0"	//From file: uplcnc.pup2
#define ANALOG_VELOCITY_COMMAND "1"	//From file: uplcnc.pup2
#define ANALOG_CURRENT_COMMAND "2"	//From file: uplcnc.pup2
#define ANALOG_FORCE_FEEDBACK "3"	//From file: uplcnc.pup2
#define ANALOG_FORCE_COMMAND "4"	//From file: uplcnc.pup2
#define ANALOG_JOYSTICK_INPUT "5"	//From file: uplcnc.pup2
#define ANALOG_TORQUE_COMP_INPUT "6"	//From file: uplcnc.pup2
#define ANALOG_INPUT_REVERSE_TORQUE_LIMIT "7"	//From file: uplcnc.pup2
#define ANALOG_INPUT_FORWARD_TORQUE_LIMIT "8"	//From file: uplcnc.pup2
#define ANALOG_INPUT_TACHO_FEEDBACK "9"	//From file: uplcnc.pup2
#define ANALOG_INPUT_POSITION_FEEDBACK "10"	//From file: uplcnc.pup2
#define EVENT_TYPE_SINGLE "0"	//From file: uplcnc.pup2
#define EVENT_TYPE_BY_GAP "1"	//From file: uplcnc.pup2
#define EVENT_TYPE_TABLE "2"	//From file: uplcnc.pup2
#define EVENT_TYPE_TABLE_HARDWARE "3"	//From file: uplcnc.pup2
#define EVENT_TYPE_TRIG_NOW "4"	//From file: uplcnc.pup2
#define EVENT_TYPE_MAX "4"	//From file: uplcnc.pup2
#define CON_FLT_ABORT "1001"	//From file: uplcnc.pup2
#define CON_FLT_SHORT "1002"	//From file: uplcnc.pup2
#define CON_FLT_ENCODER_ERROR "1003"	//From file: uplcnc.pup2
#define CON_FLT_WATCH_DOG "1004"	//From file: uplcnc.pup2
#define CON_FLT_DEAD_TIME "1005"	//From file: uplcnc.pup2
#define CON_FLT_HALLS_DISCONNECTED "1006"	//From file: uplcnc.pup2
#define CON_FLT_MOTOR_STUCK "1007"	//From file: uplcnc.pup2
#define CON_FLT_BUS_OVER_VOLTAGE "1008"	//From file: uplcnc.pup2
#define CON_FLT_BUS_UNDER_VOLTAGE "1009"	//From file: uplcnc.pup2
#define CON_FLT_LOGIC_OVER_VOLTAGE "1010"	//From file: uplcnc.pup2
#define CON_FLT_LOGIC_UNDER_VOLTAGE "1011"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_BUS_CURRENT "1012"	//From file: uplcnc.pup2
#define CON_FLT_PHASE_A_CURRENT "1013"	//From file: uplcnc.pup2
#define CON_FLT_PHASE_B_CURRENT "1014"	//From file: uplcnc.pup2
#define CON_FLT_PHASE_C_CURRENT "1015"	//From file: uplcnc.pup2
#define CON_FLT_MOTOR_CURRENT "1016"	//From file: uplcnc.pup2
#define CON_FLT_OVER_DRIVER_POWER "1017"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_IPM_TEMP "1018"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_VELOCITY "1019"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_POS_ERR "1020"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_VEL_ERR "1021"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_CPU_TEMP "1022"	//From file: uplcnc.pup2
#define CON_FLT_BUS_OVER_VOLTAGE_ABS "1023"	//From file: uplcnc.pup2
#define CON_FLT_STO1 "1024"	//From file: uplcnc.pup2
#define CON_FLT_OVERCURR_A "1025"	//From file: uplcnc.pup2
#define CON_FLT_AUX_ENC_ERROR "1026"	//From file: uplcnc.pup2
#define CON_FLT_IPM_FAULT "1027"	//From file: uplcnc.pup2
#define CON_FLT_UNKNOWN_ENCODER_TYPE "1028"	//From file: uplcnc.pup2
#define CON_FLT_UNKNOWN_AUX_ENCODER_TYPE "1029"	//From file: uplcnc.pup2
#define CON_FLT_ECAM_MASTER_TOO_FAST "1030"	//From file: uplcnc.pup2
#define CON_FLT_FIFO_TOO_SMALL_ACCLERATION "1031"	//From file: uplcnc.pup2
#define CON_FLT_IMPROPER_MODULUS_USAGE "1032"	//From file: uplcnc.pup2
#define CON_FLT_BIT_FAILED "1033"	//From file: uplcnc.pup2
#define CON_FLT_STO2_OR_VCC_DRIVE "1034"	//From file: uplcnc.pup2
#define CON_FLT_CONTROL_AC_POWER_CUTOFF "1035"	//From file: uplcnc.pup2
#define CON_FLT_OVERCURR_B "1036"	//From file: uplcnc.pup2
#define CON_FLT_LINEAR_AMPLIFIER_OVER_CURR_CONT "1037"	//From file: uplcnc.pup2
#define CON_FLT_LINEAR_AMPLIFIER_OVER_VOLTAGE "1038"	//From file: uplcnc.pup2
#define CON_FLT_LINEAR_PWM_AMPLIFIER_CONFLICT "1039"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_MOTOR_TEMP "1040"	//From file: uplcnc.pup2
#define CON_FLT_RESERVED1 "1041"	//From file: uplcnc.pup2
#define CON_FLT_5V_ISO "1042"	//From file: uplcnc.pup2
#define CON_FLT_CI_DISCONNECTED "1043"	//From file: uplcnc.pup2
#define CON_FLT_MOTOR_I2T "1044"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_FORCE_ERR "1045"	//From file: uplcnc.pup2
#define CON_FLT_NO_FORCE_FEEDBACK "1046"	//From file: uplcnc.pup2
#define CON_FLT_5V_FAULT "1047"	//From file: uplcnc.pup2
#define CON_FLT_MEMBER_UNEXPECTED_MOTOR_OFF "1048"	//From file: uplcnc.pup2
#define CON_FLT_DUAL_STUCK "1049"	//From file: uplcnc.pup2
#define CON_FLT_FAULT_INPUT "1050"	//From file: uplcnc.pup2
#define CON_FLT_INRUSH_RESISTOR "1051"	//From file: uplcnc.pup2
#define CON_FLT_STO2 "1052"	//From file: uplcnc.pup2
#define CON_FLT_AMP_TYPE_ERROR "1053"	//From file: uplcnc.pup2
#define CON_FLT_MOTOR_AC_POWER_CUTOFF "1054"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_POS_ERR_OL "1055"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_VEL_ERR_OL "1056"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_FORCE_ERR_OL "1057"	//From file: uplcnc.pup2
#define CON_FLT_UNDERVOLTAGE "1058"	//From file: uplcnc.pup2
#define CON_FLT_OVERCURR_C "1059"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_BOARD_TEMP "1060"	//From file: uplcnc.pup2
#define CON_FLT_GANTRY_MEMBER_UNEXPECTED_MOTOR_OFF "1061"	//From file: uplcnc.pup2
#define CON_FLT_FAULT_INPUT_CONTROLLED_STOP "1062"	//From file: uplcnc.pup2
#define CON_FLT_VEC_MEMBER_UNEXPECTED_MOTOR_OFF "1063"	//From file: uplcnc.pup2
#define CON_FLT_ICNQC_ERROR "1064"	//From file: uplcnc.pup2
#define CON_FLT_STALL_DETECTED_AND_MOTOR_OFF "1065"	//From file: uplcnc.pup2
#define CON_FLT_VENC_MAX_NUM_PULSES_EXCEEDED "1066"	//From file: uplcnc.pup2
#define CON_FLT_ANOMALY_DETECTED "1067"	//From file: uplcnc.pup2
#define CON_FLT_ABS_ENC_ERROR "1068"	//From file: uplcnc.pup2
#define CON_FLT_ABS_ENC_CRC_ERR "1069"	//From file: uplcnc.pup2
#define CON_FLT_ABS_ENC_DISCONNECT "1070"	//From file: uplcnc.pup2
#define CON_FLT_UNSTABLE_CURR_LOOP_DETECTED "1071"	//From file: uplcnc.pup2
#define CON_FLT_HIGH_PIV_NOISE_DETECTED "1072"	//From file: uplcnc.pup2
#define CON_FLT_NO_PHASING_IS_DETECTED "1080"	//From file: uplcnc.pup2
#define CON_FLT_CPU_BG_WATCHDOG "1081"	//From file: uplcnc.pup2
#define MOTION_MODE_JOG "0"	//From file: uplcnc.pup2
#define MOTION_MODE_PTP "1"	//From file: uplcnc.pup2
#define MOTION_MODE_PTP_REP "2"	//From file: uplcnc.pup2
#define MOTION_MODE_CNCA "11"	//From file: uplcnc.pup2
#define MOTION_STATUS "7"	//From file: uplcnc.pup2
#define MOTION_END "0"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_LINEAR "1"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_ARC "2"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_SET_VECTOR_PARAMS "5"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_CORNER_PARAMS "6"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_DOUTPORT_WRITE "8"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_ARRAY_WRITE "9"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_WAIT_ARRAY "12"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_AUTOMATIC_CORNER "14"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_ARRAY_WRITE_MULTIPLE "17"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_ARRAY_WRITE_MULTIPLE_WAIT "18"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_WAIT_INPUT "21"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_SPATIAL_EVENTS_SETUP "22"	//From file: uplcnc.pup2
#define CNC_SEGMENT_TYPE_SPATIAL_EVENTS "23"	//From file: uplcnc.pup2
#define NONINV_UNUSED_MASK "0x00FFFFFF"	//From file: uplcnc.pup2
#define ONEINV_UNUSED_MASK "0x000FFFFF"	//From file: uplcnc.pup2
#define TWOINV_UNUSED_MASK "0x0000FFFF"	//From file: uplcnc.pup2
#define THREEINV_UNUSED_MASK "0x00000FFF"	//From file: uplcnc.pup2
#define FOURINV_UNUSED_MASK "0x000000FF"	//From file: uplcnc.pup2
#define FIVEINV_UNUSED_MASK "0x0000000F"	//From file: uplcnc.pup2
#define ARRAY_TYPE_GENDATA "0"	//From file: uplcnc.pup2
#define ARRAY_TYPE_USERPARAM "1"	//From file: uplcnc.pup2
#define INPUT_SELECTION_DIGITAL "0"	//From file: uplcnc.pup2
#define INPUT_SELECTION_ANALOG "1"	//From file: uplcnc.pup2
#define CNC_TRIG_NONE "0"	//From file: uplcnc.pup2
#define CNC_TRIG_GT "1"	//From file: uplcnc.pup2
#define CNC_TRIG_EQ "2"	//From file: uplcnc.pup2
#define CNC_TRIG_NE "3"	//From file: uplcnc.pup2
#define CNC_TRIG_LT "4"	//From file: uplcnc.pup2
#define CNC_TRIG_RIS_EDGE "5"	//From file: uplcnc.pup2
#define CNC_TRIG_FALL_EDGE "6"	//From file: uplcnc.pup2
#define CNC_TRIG_MANUAL "7"	//From file: uplcnc.pup2
#define CNC_TRIG_CHANGED "8"	//From file: uplcnc.pup2

//Tasks definitions
#define main 1

//Functions definitions
#define uplMotionProfileConfig 5
#define uplMotionPTPRelative 6
#define uplMotionPTPAbsolute 7
#define uplMotionPTPRelativeRep 8
#define uplMotionPTPAbsoluteRep 9
#define uplMotionJOG 10
#define uplWait2EndOfMotion 11
#define uplMotionStop 12
#define uplMotorOn 13
#define uplMotorOff 14
#define uplMotionCNCLinear1 15
#define uplMotionCNCLinear2 16
#define uplMotionCNCLinear3 17
#define uplMotionCNCLinear4 18
#define uplMotionCNCLinear5 19
#define uplMotionCNCLinear6 20
#define uplCNCARrcMotion 21
#define uplCNCSetVectorParams 22
#define uplCNCSetCornerParams 23
#define uplCNCDOutPortWrite 24
#define uplCNCArrayWrite 25
#define uplCNCWaitUsingUserArray 26
#define uplCNCAutomaticCornerMotion 27
#define uplCNCArrayWriteMultiple 28
#define uplCNCArrayWriteMultipleWait 29
#define uplCNCWaitInput 30
#define uplCNCSpatialEventsSetup 31
#define uplCNCSpatialEvents 32
#define uplCNCSetSpeedPercent 33
#define uplCNCStop 34
#define uplCNCPause 35
#define uplCNCResume 36
#define uplCNCStepModeOn 37
#define uplCNCDoStep 38
#define uplCNCStepModeOff 39
